name: plugin-api dev

on:
  push:
    branches: 
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout SeqsLab Plugin API Code
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Update apt-get
        run: sudo apt-get update

      - name: Install GnuPG
        run: sudo apt-get -y install gpg

      - name: Import GPG
        uses: crazy-max/ghaction-import-gpg@v5.1.0
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Prepare Version Name
        id: name
        run: |
          echo "::set-output name=BRANCH_NAME::$(echo DEV${GITHUB_REF#refs/heads}-SNAPSHOT | sed 's/\//_/g')"    

      - name: maven-settings-xml-action
        uses: whelk-io/maven-settings-xml-action@v20
        with:
          servers: >
            [
              {
                "id": "nexus",
                "username": "admin",
                "password": "${{ secrets.NEXUS_PASSWORD }}"
              },
              {
                "id": "gpg.passphrase",
                "passphrase": "${{ secrets.GPG_PASSPHRASE }}"
              }
            ]

      - name: Show Maven Version
        run: |
          mvn -version

      - name: Build with Maven
        run: |
          mvn versions:set -DnewVersion=${{ steps.name.outputs.BRANCH_NAME }}
          mvn clean deploy -P nexus

      - uses: actions/checkout@v2
      - name: Slack Notification
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: tests
          SLACK_COLOR: '#3278BD'
          SLACK_MESSAGE: 'Test fails after commit pushed please check with links above.'
          SLACK_TITLE: Test Failure
          SLACK_USERNAME: Github Action
          SLACK_MSG_AUTHOR: $GITHUB_ACTOR
